apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: demo-sidecar
  namespace: default
spec:
    match:
      scope: Namespaced
      kinds:
        - apiGroups: ["*"]
          kinds: ["Pod"]
    applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
    location: "spec.containers[name:networking]"
    parameters:
      assign:
        value:
          name: "networking"
          imagePullPolicy: Always
          image: docker.io/centos
          command: ["/bin/bash", "-c", "sleep INF"]
